spring:
  datasource:
    url: jdbc:mysql://192.168.0.104:3306/nba?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      initial-size: 5                                               #连接池初始化大小
      min-idle: 10                                                  #最小空闲连接数
      max-active: 20                                                #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"   #不统计这些请求数据

server:
  port: 8083

#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info
    com.xdclass.search: debug

elasticsearch:
  host: localhost
  port: 9200



